# simulation_environment.py
# Tactical simulation environment with zone-based alerting
#
# This is the bridge between computer vidion and military simuation:
# - Defines a tactical area of operations (AO)
# - Divides it into zones with different threat classifications
# - Tracks entities through zones over time
# - Generates alerts when entities behave in ways of interest

import time
import numpy as np
from dataclasses import dataclass, field
from typing import Optional
from enum import Enum


# Entity States

class EntityState(Enum):
    """
    State machine for tracked entities.

    State transtitions:
    UNKNOWN -> DETECTED (first detection)
    DETECTED -> TRACKED (confirmated across multiple frames)
    TRACKED -> LOST (tracking lost)
    LOST -> TRACKED (re-acquired)
    TRACKED -> NEUTRALIZED (manually cleared by operator  -- future feature)
    """
    UNKNOWN = "UNKNOWN"
    DETECTED = "DETECTED"
    TRACKED = "TRACKED"
    LOST = "LOST"
    NEUTRALIZED = "NEUTRALIZED"


class ZoneType(Enum):
    """
    Zone classifications for the tactical area of operations.
    """
    CLEAR = "CLEAR"
    MONITORING = "MONITORING"
    RESTRICTED = "RESTRICTED"
    EXCLUSION = "EXCLUSION"     # Highest alert level


# Data Structures

@dataclass
class Zone:
    """
    A defined area in the tactical environment.
    Entities in this zone trigger specific alert behaviors.
    """
    name: str
    zone_type: ZoneType
    bounds: tuple           # (x1_pct, y1_pct, x2_pct, y2_pct) as % of frame
    color: tuple            # BGR color for visualization
    alert_on_entry: bool = True
    alert_on_dwell: bool = True
    dwell_threshold_seconds : float = 5.0


@dataclass
class TrackedEntity:
    """
    A persistent entity being monitored across multiple frames.
    Combines tracker state with simulation-level state.
    """
    entity_id: int
    class_name: str
    threat_level: str
    state: EntityState
    current_bbox: tuple
    current_center: tuple
    trajectory: list            # List of (x, y) positions
    current_zone: Optional[str]
    zone_entry_time: Optional[float]
    first_detected: float
    last_updated: float
    total_frames_tracked: int
    alerts_generated: list      # List of alert strings


@dataclass
class Alert:
    """
    An alert event generated by the simulation.
    """
    alert_id: int
    alert_type: str             # ZONE_ENTRY, DWELL, HIG_THREAT, LOST, etc.
    entity_id: int
    entity_class: str
    threat_level: str
    zone_name: Optional[str]
    message: str
    timestamp: float
    severity: str               # INFO, WARNING, CRITICAL


# Simulation Environment

class TacticalSimulation:
    """
    Manages the tactical simulation state.

    Responsibilities:
    - Maintain state for all tracked entities
    - Process zone transitions and generate alerts
    - Track simulation metrics (entity counts, alerts rates)
    - Provide data to the dashboard for visualization
    """

    def __init__(self, frame_width: int = 1280, frame_height: int = 720):
        self.frame_width = frame_width
        self.frame_height = frame_height

        self.entities = {}          # entity_id -> TrackedEntity
        self.alerts = []            # All generated alerts
        self.alert_counter = 0
        self.start_time = time.time()

        # Initialize default tactical zones
        # In a real system, these would be configurable by the operator
        self.zones = self._initialize_default_zones()

        # Metrics
        self.total_entities_seen = 0
        self.high_threat_count = 0

    def _initialize_default_zones(self) -> list:
        """
        Create default zone layout.
        Zones are defined as percentages of the frame (0.0 to 1.0)
        so they scale with any video resolution.
        """
        return [
            Zone(
                name="North Perimeter",
                zone_type=ZoneType.RESTRICTED,
                bounds=(0.0, 0.0, 1.0, 0.25),           # Top 25% of frame
                color=(0, 165, 255),                    # Orange
                dwell_threshold_seconds=3.0
            ),
            Zone(
                name="Central Exclusion Zone",
                zone_type=ZoneType.EXCLUSION,
                bounds=(0.3, 0.3, 0.7, 0.7),            # Center 40% of frame
                color=(0, 0, 255),
                dwell_threshold_seconds=2.0
            ),
            Zone(
                name="East Corridor",
                zone_type=ZoneType.MONITORING,
                bounds=(0.75, 0.25, 1.0, 0.75),         # Right side
                color=(0, 255, 255),                    # Yellow
                dwell_threshold_seconds=10.0
            ),
            Zone(
                name="West Corridor",
                zone_type=ZoneType.MONITORING,
                bounds=(0.0, 0.25, 0.25, 0.75),         # Left 
                color=(0, 255, 255),                    # Yellow
                dwell_threshold_seconds=10.0
            ),
            Zone(
                name="South Clear Zone",
                zone_type=ZoneType.CLEAR,
                bounds=(0.0, 0.75, 1.0, 1.0),           # Bottom 25%
                color=(0, 255, 0),                      # Green
                alert_on_entry=False,
                dwell_threshold_seconds=30.0
            ),
        ]

    def get_zone_for_position(self, center: tuple) -> Optional[Zone]:
        """
        Determine which zone a position falls in.
        Returns the highest-priority zone (EXCLUSION > RESTRICTED > MONITORING > CLEAR).
        """
        cx_pct = center[0] / self.frame_width
        cy_pct = center[1] / self.frame_height

        priority_order = [
            ZoneType.EXCLUSION,
            ZoneType.RESTRICTED,
            ZoneType.MONITORING,
            ZoneType.CLEAR
        ]

        # Check zones in priority order
        for zone_type in priority_order:
            for zone in self.zones:
                if zone.zone_type == zone_type:
                    x1, y1, x2, y2 = zone.bounds
                    if x1 <= cx_pct <= x2 and y1 <= cy_pct <= y2:
                        return zone

        return None

    def _generate_alert(
            self,
            alert_type: str,
            entity: TrackedEntity,
            zone: Optional[Zone],
            message: str,
            severity: str
    ) -> Alert:
        """
        Create and store an alert.
        """
        self.alert_counter += 1

        alert = Alert(
            alert_id=self.alert_counter,
            alert_type=alert_type,
            entity_id=entity.entity_id,
            entity_class=entity.class_name,
            threat_level=entity.threat_level,
            zone_name=zone.name if zone else None,
            message=message,
            timestamp=time.time(),
            severity=severity
        )

        self.alerts.append(alert)
        entity.alerts_generated.append(message)

        return alert

    def update(self, tracked_entities_from_sort: list) -> list:
        """
        Update simulation state with new tracking data.

        tracked_entities_from_sort: List of KalmanBoxTracker objects
        Returns: List of new Alert objects generated this frame
        """
        new_alerts = []
        current_time = time.time()

        # Track which entity IDs we've seen this frame
        seen_ids = set()

        for tracker in tracked_entities_from_sort:
            entity_id = tracker.id
            seen_ids.add(entity_id)

            bbox = tracker.get_bbox()
            center = tracker.get_center()

            # Determine zone for this position
            current_zone = self.get_zone_for_position(center)
            zone_name = current_zone.name if current_zone else None

            if entity_id not in self.entities:
                # New entity -- create simulation record
                self.total_entities_seen += 1

                entity = TrackedEntity(
                    entity_id=entity_id,
                    class_name=tracker.class_name,
                    threat_level=tracker.threat_level,
                    state=EntityState.DETECTED,
                    current_bbox=bbox,
                    current_center=center,
                    trajectory=[center],
                    current_zone=zone_name,
                    zone_entry_time=current_time if current_zone else None,
                    first_detected=current_time,
                    last_updated=current_time,
                    total_frames_tracked=1,
                    alerts_generated=[]
                )
                self.entities[entity_id] = entity

                if tracker.threat_level == "HIGH":
                    self.high_threat_count += 1

                # Alert for high-threat new detection
                if  tracker.threat_level == "HIGH":
                    alert = self._generate_alert(
                        "HIGH_THREAT_DETECTED",
                        entity,
                        current_zone,
                        f"HIGH THREAT: {tracker.class_name.upper()} "
                        f"detected (Entity {entity_id})"
                        + (f" in {zone_name}" if zone_name else ""),
                        "CRITICAL"
                    )
                    new_alerts.append(alert)

                # Alert for zone entry
                if current_zone and current_zone.alert_on_entry:
                    severity_map = {
                        ZoneType.EXCLUSION: "CRITICAL",
                        ZoneType.RESTRICTED: "WARNING",
                        ZoneType.MONITORING: "INFO",
                        ZoneType.CLEAR: "INFO"
                    }
                    alert = self._generate_alert(
                        "ZONE_ENTRY",
                        entity,
                        current_zone,
                        f"Entity {entity_id} ({tracker.class_name}) "
                        f"entered {zone_name}",
                        severity_map.get(current_zone.zone_type, "INFO")
                    )
                    new_alerts.append(alert)
                else:
                    # Existing entity -- update state
                    entity = self.entities[entity_id]
                    prev_zone = entity.current_zone

                    entity.current_bbox = bbox
                    entity.current_center = center
                    entity.state = EntityState.TRACKED
                    entity.last_updated = current_time
                    entity.total_frames_tracked += 1
                    entity.trajectory.append(center)

                    # Keep trajectory manageable
                    if len(entity.trajectory) > 100:
                        entity.trajectory.pop(0)

                    # Zone transition detection
                    if zone_name !=  prev_zone:
                        entity.current_zone = zone_name
                        entity.zone_entry_time = current_time if current_zone else None

                        if current_zone and current_zone.alert_on_entry:
                            severity_map = {
                                ZoneType.EXCLUSION: "CRITICAL",
                                ZoneType.RESTRICTED: "WARNING",
                                ZoneType.MONITORING: "INFO",
                                ZoneType.CLEAR: "INFO"
                            }
                            alert = self._generate_alert(
                                "ZONE_ENTRY",
                                entity,
                                current_time,
                                f"Entity {entity_id} ({tracker.class_name}) "
                                f"moved from {prev_zone or 'unknown'} to {zone_name}",
                                severity_map.get(current_zone.zone_type, "INFO")
                            )
                            new_alerts.append(alert)

                    # Dwell time alert
                    if (current_zone and current_zone.alert_on_dwell and entity.zone_entry_time):
                        dwell_time = current_time - entity.zone_entry_time

                        if dwell_time >= current_zone.dwell_threshold_seconds:
                            # Only alert once per threshold crossing
                            dwell_alert_key = f"dwell_{entity_id}_{zone_name}"
                            if dwell_alert_key not in entity.alert_generated:
                                entity.alerts_generated.append(dwell_alert_key)
                                severity_map = {
                                    ZoneType.EXCLUSION: "CRITICAL",
                                    ZoneType.RESTRICTED: "WARNING",
                                    ZoneType.MONITORING: "INFO"
                                }
                                alert = self._generate_alert(
                                    "DWELL_ALERT",
                                    entity,
                                    current_zone,
                                    f"Entity {entity_id} ({tracker.class_name}) "
                                    f"dwelling in {zone_name} "
                                    f"for {dwell_time:.0f}s",
                                    severity_map.get(current_zone.zone_type, "INFO")
                                )
                                new_alerts.append(alert)

        # Mark entities not seen this frame as LOST
        for entity_id, entity in self.entities.items():
            if entity_id not in seen_ids:
                if entity.state == EntityState.TRACKED:
                    entity.state = EntityState.LOST
                    entity.last_updated = current_time

        return new_alerts

    def get_dashboard_data(self) -> dict:
        """
        Package all simulation state for the dashboard.
        Called every frame to update the UI.
        """
        current_time = time.time()
        elapsed = current_time - self.start_time

        # Activate entities (currently tracked)
        active = [
            e for e in self.entities.values()
            if e.state == EntityState.TRACKED
        ]

        # Threat breakdown
        threat_counts = {"HIGH": 0, "MEDIUM": 0, "LOW": 0}
        class_counts = {}

        for entity in active:
            threat_counts[entity.threat_level] = (
                threat_counts.get(entity.threat_level, 0) + 1
            )

        # Recent alerts (last 20)
        recent_alerts = sorted(
            self.alerts, key=lambda a: a.timestamp, reverse=True
        )[:20]

        # Zone occupancy
        zone_occupancy = {z.name: 0 for z in self.zones}
        for entity in active:
            if entity.current_zone in zone_occupancy:
                zone_occupancy[entity.current_zone] += 1

        return {
            "elapsed_seconds": elapsed,
            "total_entities_seen": self.total_entities_seen,
            "active_entity_count": len(active),
            "active_entities": active,
            "threat_counts": threat_counts,
            "class_counts": class_counts,
            "total_alerts": len(self.alerts),
            "recent_alerts": recent_alerts,
            "zone_occupancy": zone_occupancy,
            "zones": self.zones,
            "high_threat_count": self.high_threat_count
        }